### ISSUE TITLE
Follow + Join Section 

### ISSUE THREAD

**Issue by aremu-smog** [BigTi0/wizkid-official-dub#5]
Kindly take a good look at the original website very well

**Comment by BigTi0** [comment]
i still do not get it

**Comment by aremu-smog** [comment]
Check the original website and compare with what you have.
Aremu Oluwgbamila

**Comment by BigTi0** [comment]
I think i fixed it.
will push the upload in a few

**Comment by aremu-smog** [comment]
Kindly let me know once you have pushed all updates. Well-done.

Aremu Oluwgbamila
